name: CI

on:
    pull_request:
    push:
        branches:
            - master
        tags:
            - "**"

jobs:
    coding-standards:
        name: "Coding Standards"

        runs-on: ubuntu-latest

        steps:
            -   name: "Checkout"
                uses: actions/checkout@master
                with:
                    fetch-depth: 1

            -   name: "PHP-CS-Fixer"
                uses: docker://oskarstark/php-cs-fixer-ga
                with:
                    args: --diff --diff-format=udiff --using-cache=no --verbose --dry-run

    static-code-analysis:
        name: "Static Code Analysis"

        runs-on: ubuntu-latest

        steps:
            -   name: "Checkout"
                uses: actions/checkout@master
                with:
                    fetch-depth: 1

            -   name: PHPStan
                uses: docker://oskarstark/phpstan-ga
                with:
                    args: analyse

            -   name: PHP Syntax Checker (Lint)
                uses: StephaneBour/actions-php-lint@7.3
                with:
                    dir: './src'

    php-cs-fixer:
          name: check php-cs-fixer codestyles
          runs-on: ubuntu-latest
          steps:
              - uses: actions/checkout@master
              - name: Setup PHP
                uses: shivammathur/setup-php@master
                with:
                    php-version: 7.1
                    extension-csv: intl
                coverage: none # disable xdebug, pcov
          - run: composer global require friendsofphp/php-cs-fixer && ~/.composer/vendor/bin/php-cs-fixer fix --diff --dry-run
