name: CI

on: [push, pull_request]

jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: PHP-CS-Fixer
      uses: docker://oskarstark/php-cs-fixer-ga
#      with:
#        args: --diff --dry-run

      #uses: OskarStark/php-cs-fixer-ga@2.15.3
#        with:
#          args: --config=.project.php_cs --diff --dry-run
